{
    "Point": {
        "type": "struct",
        "errors": []
    },
    "calculate_distance": {
        "type": "function",
        "errors": []
    },
    "main": {
        "type": "function",
        "errors": [
            {
                "type": "COMPILE_ERROR",
                "message": "    Updating crates.io index\n     Locking 6 packages to latest compatible versions\n   Compiling proc-macro2 v1.0.92\n   Compiling unicode-ident v1.0.14\n   Compiling syn v1.0.109\n   Compiling libc v0.2.169\n   Compiling quote v1.0.38\n   Compiling sactor_proc_macros v0.1.0 (/home/Anonymous/.cache/sactor-attempt/build_attempt/sactor_proc_macros)\n   Compiling build_attempt v0.1.0 (/home/Anonymous/.cache/sactor-attempt/build_attempt)\nerror[E0428]: the name `calculate_distance` is defined multiple times\n  --> src/lib.rs:18:1\n   |\n8  | pub fn calculate_distance(p1: Point, p2: Point) -> f32 {\n   | ------------------------------------------------------ previous definition of the value `calculate_distance` here\n...\n18 | fn calculate_distance(p1: Point, p2: Point) -> f32 {\n   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `calculate_distance` redefined here\n   |\n   = note: `calculate_distance` must be defined only once in the value namespace of this module\n\nerror[E0428]: the name `Point` is defined multiple times\n  --> src/lib.rs:14:1\n   |\n4  | pub struct Point {\n   | ---------------- previous definition of the type `Point` here\n...\n14 | pub struct Point {\n   | ^^^^^^^^^^^^^^^^ `Point` redefined here\n   |\n   = note: `Point` must be defined only once in the type namespace of this module\n\nerror[E0119]: conflicting implementations of trait `Debug` for type `Point`\n  --> src/lib.rs:13:10\n   |\n3  | #[derive(Copy, Clone, Debug)]\n   |                       ----- first implementation here\n...\n13 | #[derive(Debug)]\n   |          ^^^^^ conflicting implementation for `Point`\n   |\n   = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)\n\nSome errors have detailed explanations: E0119, E0428.\nFor more information about an error, try `rustc --explain E0119`.\nerror: could not compile `build_attempt` (lib) due to 3 previous errors\n"
            }
        ]
    }
}